version: "3.9"
services:
  dev-finder-db:
    image: postgres
    restart: always
    container_name: code-with-friends-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: saikiran@16
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
